development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  host: lab.redistogo.com
  password: <%= ENV["REDISTOGO_PASSWORD"] %>
  port: 9648
  inline: true
  timeout: 1
